---
title: "Info Visualisation Notebook"
output: info_vis_notebook
---

Set working directory

```{r}
# Ana's WD
# setwd("C:/Users/Ana-Maria's Laptop/Documents/GitHub/infoVisualization")

# Andrei's WD
# setwd("C:/Users/andre/Documents/infoVisualization/")
```

Imports - libraries and read dataset

```{r}
library(ggplot2)
library(astsa)
library(gganimate)
library(gapminder)
library(ggmap)
library(ggiraph)

```

```{r}
earthquakes_csv = "eartquakes_Romania.csv"
df <- read.csv(file = earthquakes_csv)
```

```{r}
# convert time column to R timestap
df$time <- gsub('T', ' ', df$time)
df$time <- gsub('Z', '', df$time)
df$time <- as.POSIXct(df$time, format="%Y-%m-%d %H:%M:%OS", tz=Sys.timezone())

#split timestamp into date and time
df$timeYear <- as.Date(df$time)
df$timeDay <- format(df$time, "%H:%M:%OS")

df$year <- format(df$time, "%Y")
df$month <- format(df$time, "%m")

df$yearInt <- as.integer(df$year)
```

```{r}
### CHECK FOR STATIONARITY AND MAKE 
### DATA STATIONARY

### Magnitude time series

get_ts_matrix <- function(ts_magnitude) {
  time <- 0
  mag <- 0
  for (index in 1:nrow(ts_magnitude)) {
    time[index] <- ts_magnitude[index,1]
    mag[index] <- ts_magnitude[index,2]
  }
  mag_matrix <- matrix(ts_magnitude$df.mag, 
                       nrow =length(ts_magnitude$df.timeYear),
                       dimnames = list(ts_magnitude$df.timeYear, "data"))
  return(mag_matrix)
}

ts_magnitude <- data.frame(df$timeYear, df$mag)

ts_magnitude_plot <- ggplot(ts_magnitude, aes(x=df.timeYear, y=df.mag)) +
  ggtitle("Magnitude time series") +
  geom_line() + 
  xlab("")

ts_magnitude_plot

mag_matrix <- get_ts_matrix(ts_magnitude)
acf2(ts(mag_matrix))

### First diff time series
ts_magnitude$df.mag<- c(0, diff(df$mag))

ts_diff_magnitude_plot <- ggplot(ts_magnitude, aes(x=df.timeYear, y=df.mag)) +
  ggtitle("First diff - Magnitude time series") +
  geom_line() + 
  xlab("")

ts_diff_magnitude_plot

diff_mag_matrix <- get_ts_matrix(ts_magnitude)
acf2(ts(diff_mag_matrix))

### Second diff time series

### ts_magnitude$df.mag<- c(0, diff(ts_magnitude$df.mag))

ts_second_diff_magnitude_plot <- ggplot(ts_magnitude, aes(x=df.timeYear, y=df.mag)) +
  ggtitle("Second diff - Magnitude time series") +
  geom_line() + 
  xlab("")

ts_second_diff_magnitude_plot

second_diff_mag_matrix <- get_ts_matrix(ts_magnitude)
acf2(ts(second_diff_mag_matrix))

### ACF indicates q
### PACF indicates p
### arima(p,diff,q)

data <- ts(diff_mag_matrix)

ma1<-arima(data, order=c(0,0,1))

ar1<-arima(data ,order=c(1,0,0))
ar2<-arima(data ,order=c(2,0,0))
ar3<-arima(data ,order=c(3,0,0))
ar4<-arima(data ,order=c(4,0,0))
```

```{r}
my_model <- arima(data, order=c(1,2,2))
stdres <- my_model$residuals/sqrt(my_model$sigma2)
plot(my_model$residuals, main = "Chosen model - ARIMA(1, 3, 2) - Residuals")
qqnorm(stdres, main = "Chosen model - ARIMA(1, 3, 2) - Normal Q-Q Plot of Std Residuals")

shapiro.test(residuals(my_model))
```

```{r}
my_forecast = predict(arima(ts(mag_matrix), order=c(1,2,2)), n.ahead=30)
# ts.plot(ts(mag_matrix), 
#        my_forecast$pred,  
#        col=1:2,
#        lwd=1)

my_forecast
ggplot(ts_magnitude, aes(x=df.timeYear, y=df.mag)) +
  ggtitle("Magnitude time series") +
  geom_line() + 
  xlab("")

ts_magnitude
```

```{r}
year_earthquakes <- aggregate(list("MagMean"=df[, 5]), list("Year"=df$year), mean)

year_df <- data.frame(year_earthquakes$Year, year_earthquakes$MagMean)
     year_df      
     
plot(year_df)
year_df <- ggplot(year_df, aes(x=year_earthquakes.Year, y=year_earthquakes.MagMean)) +
  geom_line() + 
  xlab("")

year_df
```

